name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install
        working-directory: chatbot_baby_yoda

      - name: Build Angular
        run: npm run build -- --base-href /baby_yoda_chatbot-sistemas_expertos/
        working-directory: chatbot_baby_yoda

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: chatbot_baby_yoda/dist/chatbot_baby_yoda/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4